//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJS_Tree_with_Web_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public System.Guid Id { get; set; }
        public int NumericId { get; set; }
        public System.Guid ParentId { get; set; }
        public string Name { get; set; }
    }
}
